"""Core SRD spells for the D&D 5e combat system.

Each spell has:
  name, level, school, casting_ability,
  effect (description), damage_dice, healing_dice,
  attack (bool — spell attack vs save),
  save_ability (for save-based spells).
"""

SRD_SPELLS: dict[str, dict] = {
    # Cantrips (level 0)
    "fire_bolt": {
        "name": "Fire Bolt",
        "level": 0,
        "school": "evocation",
        "casting_ability": "intelligence",
        "effect": "A mote of fire streaks toward a creature. Make a ranged spell attack. On hit, deals fire damage.",
        "damage_dice": "1d10",
        "attack": True,
    },
    "sacred_flame": {
        "name": "Sacred Flame",
        "level": 0,
        "school": "evocation",
        "casting_ability": "wisdom",
        "effect": "Flame-like radiance descends on a creature. Target must make DEX save or take radiant damage.",
        "damage_dice": "1d8",
        "save_ability": "dexterity",
    },
    "eldritch_blast": {
        "name": "Eldritch Blast",
        "level": 0,
        "school": "evocation",
        "casting_ability": "charisma",
        "effect": "A beam of crackling energy streaks toward a creature. Make a ranged spell attack.",
        "damage_dice": "1d10",
        "attack": True,
    },
    "ray_of_frost": {
        "name": "Ray of Frost",
        "level": 0,
        "school": "evocation",
        "casting_ability": "intelligence",
        "effect": "A frigid beam of blue-white light streaks toward a creature. On hit, deals cold damage and reduces speed by 10ft.",
        "damage_dice": "1d8",
        "attack": True,
    },
    # Level 1
    "magic_missile": {
        "name": "Magic Missile",
        "level": 1,
        "school": "evocation",
        "casting_ability": "intelligence",
        "effect": "Three darts of magical force each deal 1d4+1 force damage. They automatically hit.",
        "damage_dice": "3d4+3",
    },
    "cure_wounds": {
        "name": "Cure Wounds",
        "level": 1,
        "school": "evocation",
        "casting_ability": "wisdom",
        "effect": "A creature you touch regains hit points.",
        "healing_dice": "1d8",
    },
    "healing_word": {
        "name": "Healing Word",
        "level": 1,
        "school": "evocation",
        "casting_ability": "wisdom",
        "effect": "A creature of your choice that you can see within range regains hit points (bonus action).",
        "healing_dice": "1d4",
    },
    "shield": {
        "name": "Shield",
        "level": 1,
        "school": "abjuration",
        "casting_ability": "intelligence",
        "effect": "An invisible barrier of magical force appears. +5 AC until the start of your next turn, including against the triggering attack.",
    },
    "thunderwave": {
        "name": "Thunderwave",
        "level": 1,
        "school": "evocation",
        "casting_ability": "intelligence",
        "effect": "A wave of thunderous force sweeps out. Each creature in a 15-foot cube must make a CON save.",
        "damage_dice": "2d8",
        "save_ability": "constitution",
    },
    "burning_hands": {
        "name": "Burning Hands",
        "level": 1,
        "school": "evocation",
        "casting_ability": "intelligence",
        "effect": "A thin sheet of flames shoots forth. Each creature in a 15-foot cone must make a DEX save.",
        "damage_dice": "3d6",
        "save_ability": "dexterity",
    },
    "guiding_bolt": {
        "name": "Guiding Bolt",
        "level": 1,
        "school": "evocation",
        "casting_ability": "wisdom",
        "effect": "A flash of light streaks toward a creature. Make a ranged spell attack. Next attack against the target has advantage.",
        "damage_dice": "4d6",
        "attack": True,
    },
    "inflict_wounds": {
        "name": "Inflict Wounds",
        "level": 1,
        "school": "necromancy",
        "casting_ability": "wisdom",
        "effect": "Make a melee spell attack. On a hit, the target takes necrotic damage.",
        "damage_dice": "3d10",
        "attack": True,
    },
    # Level 2
    "scorching_ray": {
        "name": "Scorching Ray",
        "level": 2,
        "school": "evocation",
        "casting_ability": "intelligence",
        "effect": "You create three rays of fire and hurl them. Make a ranged spell attack for each ray.",
        "damage_dice": "2d6",
        "attack": True,
    },
    "hold_person": {
        "name": "Hold Person",
        "level": 2,
        "school": "enchantment",
        "casting_ability": "wisdom",
        "effect": "Choose a humanoid. The target must succeed on a WIS save or be paralyzed.",
        "save_ability": "wisdom",
    },
    "spiritual_weapon": {
        "name": "Spiritual Weapon",
        "level": 2,
        "school": "evocation",
        "casting_ability": "wisdom",
        "effect": "You create a floating, spectral weapon. Make a melee spell attack dealing force damage.",
        "damage_dice": "1d8",
        "attack": True,
    },
    # Level 3
    "fireball": {
        "name": "Fireball",
        "level": 3,
        "school": "evocation",
        "casting_ability": "intelligence",
        "effect": "A bright streak flashes to a point and blossoms into an explosion. Each creature in a 20-foot radius must make a DEX save.",
        "damage_dice": "8d6",
        "save_ability": "dexterity",
    },
    "lightning_bolt": {
        "name": "Lightning Bolt",
        "level": 3,
        "school": "evocation",
        "casting_ability": "intelligence",
        "effect": "A stroke of lightning in a 100-foot line. Each creature must make a DEX save.",
        "damage_dice": "8d6",
        "save_ability": "dexterity",
    },
    "counterspell": {
        "name": "Counterspell",
        "level": 3,
        "school": "abjuration",
        "casting_ability": "intelligence",
        "effect": "You attempt to interrupt a creature in the process of casting a spell. Automatically counters spells of 3rd level or lower.",
    },
    "revivify": {
        "name": "Revivify",
        "level": 3,
        "school": "necromancy",
        "casting_ability": "wisdom",
        "effect": "You touch a creature that has died within the last minute. That creature returns to life with 1 hit point.",
        "healing_dice": "0d0+1",
    },
    # Level 4
    "polymorph": {
        "name": "Polymorph",
        "level": 4,
        "school": "transmutation",
        "casting_ability": "intelligence",
        "effect": "This spell transforms a creature into a new form. Target must make WIS save (unwilling).",
        "save_ability": "wisdom",
    },
}
