"""Add images column to messages

Revision ID: 79a25e0fdbea
Revises: 
Create Date: 2026-03-08 12:44:18.040007
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '79a25e0fdbea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('images', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_rel_type'), 'rpg_relationships', ['session_id', 'relationship'], unique=False)
    op.create_index(op.f('idx_rel_target'), 'rpg_relationships', ['session_id', 'target_type', 'target_id'], unique=False)
    op.create_index(op.f('idx_rel_source'), 'rpg_relationships', ['session_id', 'source_type', 'source_id'], unique=False)
    op.create_index(op.f('idx_gamesession_campaign'), 'rpg_game_sessions', ['campaign_id'], unique=False)
    op.drop_column('messages', 'images')
    op.create_index(op.f('idx_game_memories_session_number'), 'game_memories', ['session_number'], unique=False)
    op.create_index(op.f('idx_game_memories_memory_type'), 'game_memories', ['memory_type'], unique=False)
    op.create_index(op.f('idx_game_memories_entity_type'), 'game_memories', ['entity_type'], unique=False)
    op.create_table('vec_memories_vector_chunks00',
    sa.Column('rowid', sa.NullType(), nullable=True),
    sa.Column('vectors', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('fts_memories_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vec_memories_info',
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('vec_memories_rowids',
    sa.Column('rowid', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.NullType(), nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), nullable=True),
    sa.Column('chunk_offset', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('fts_memories_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fts_memories_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('fts_memories_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('vec_memory_map',
    sa.Column('rowid', sa.INTEGER(), nullable=True),
    sa.Column('memory_id', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('rowid'),
    sa.UniqueConstraint('memory_id')
    )
    op.create_table('vec_chunks_vector_chunks00',
    sa.Column('rowid', sa.NullType(), nullable=True),
    sa.Column('vectors', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('vec_chunks_chunks',
    sa.Column('chunk_id', sa.INTEGER(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('validity', sa.BLOB(), nullable=False),
    sa.Column('rowids', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('vec_chunks_rowids',
    sa.Column('rowid', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.NullType(), nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), nullable=True),
    sa.Column('chunk_offset', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('fts_memories_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vec_memories',
    sa.Column('rowid', sa.NullType(), nullable=True),
    sa.Column('embedding', sa.NullType(), nullable=True)
    )
    op.create_table('vec_memories_chunks',
    sa.Column('chunk_id', sa.INTEGER(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('validity', sa.BLOB(), nullable=False),
    sa.Column('rowids', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('vec_chunks_info',
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('fts_memories',
    sa.Column('content', sa.NullType(), nullable=True),
    sa.Column('entity_names', sa.NullType(), nullable=True),
    sa.Column('memory_id', sa.NullType(), nullable=True)
    )
    op.create_table('vec_chunks',
    sa.Column('rowid', sa.NullType(), nullable=True),
    sa.Column('embedding', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
